const fishData = [

    
    {"species":"Anchovy", "url": "https://dodo.ac/np/images/7/7f/Anchovy_%28Fish%29_NH_Icon.png"},
    {"species":"Angelfish", "url": "https://dodo.ac/np/images/c/cd/Angelfish_NH_Icon.png"},
    {"species":"Arapaima", "url": "https://dodo.ac/np/images/b/b1/Arapaima_NH_Icon.png"},
    {"species":"Arowana", "url": "https://dodo.ac/np/images/6/67/Arowana_NH_Icon.png"},
    {"species":"Barred knifejaw", "url": "https://dodo.ac/np/images/d/d5/Barred_Knifejaw_NH_Icon.png"},
    {"species":"Barreleye", "url": "https://dodo.ac/np/images/e/e0/Barreleye_NH_Icon.png"},
    {"species":"Betta", "url": "https://dodo.ac/np/images/0/0b/Betta_NH_Icon.png"},
    {"species":"Bitterling", "url": "https://dodo.ac/np/images/4/4d/Bitterling_NH_Icon.png"},
    {"species":"Black bass", "url": "https://dodo.ac/np/images/0/00/Black_Bass_NH_Icon.png"},
    {"species":"Blowfish", "url": "https://dodo.ac/np/images/9/95/Blowfish_NH_Icon.png"},
    {"species":"Blue marlin", "url": "https://dodo.ac/np/images/2/2a/Blue_Marlin_NH_Icon.png"},
    {"species":"Bluegill", "url": "https://dodo.ac/np/images/0/0c/Bluegill_NH_Icon.png"},
    {"species":"Butterfly fish", "url": "https://dodo.ac/np/images/4/47/Butterfly_Fish_NH_Icon.png"},
    {"species":"Carp", "url": "https://dodo.ac/np/images/5/5d/Carp_NH_Icon.png"},
    {"species":"Catfish", "url": "https://dodo.ac/np/images/0/0d/Catfish_NH_Icon.png"},
    {"species":"Char", "url": "https://dodo.ac/np/images/8/80/Char_NH_Icon.png"},
    {"species":"Cherry salmon", "url": "https://dodo.ac/np/images/d/db/Cherry_Salmon_NH_Icon.png"},
    {"species":"Clown fish", "url": "https://dodo.ac/np/images/4/4f/Clown_Fish_NH_Icon.png"},
    {"species":"Coelacanth", "url": "https://dodo.ac/np/images/4/45/Coelacanth_NH_Icon.png"},
    {"species":"Crawfish", "url": "https://dodo.ac/np/images/9/96/Crawfish_NH_Icon.png"},
    {"species":"Crucian carp", "url": "https://dodo.ac/np/images/f/f2/Crucian_Carp_NH_Icon.png"},
    {"species":"Dab", "url": "https://dodo.ac/np/images/1/1f/Dab_NH_Icon.png"},
    {"species":"Dace", "url": "https://dodo.ac/np/images/d/db/Dace_NH_Icon.png"},
    {"species":"Dorado", "url": "https://dodo.ac/np/images/f/fe/Dorado_NH_Icon.png"},
    {"species":"Football fish", "url": "https://dodo.ac/np/images/3/34/Football_Fish_NH_Icon.png"},
    {"species":"Freshwater goby", "url": "https://dodo.ac/np/images/e/ec/Freshwater_Goby_NH_Icon.png"},
    {"species":"Frog", "url": "https://dodo.ac/np/images/2/2f/Frog_NH_Icon.png"},
    {"species":"Gar", "url": "https://dodo.ac/np/images/a/a2/Gar_NH_Icon.png"},
    {"species":"Giant snakehead", "url": "https://dodo.ac/np/images/5/50/Giant_Snakehead_NH_Icon.png"},
    {"species":"Giant trevally", "url": "https://dodo.ac/np/images/1/17/Giant_Trevally_NH_Icon.png"},
    {"species":"Golden trout", "url": "https://dodo.ac/np/images/f/fc/Golden_Trout_NH_Icon.png"},
    {"species":"Goldfish", "url": "https://dodo.ac/np/images/7/71/Goldfish_NH_Icon.png"},
    {"species":"Great white shark", "url": "https://dodo.ac/np/images/2/20/Great_White_Shark_NH_Icon.png"},
    {"species":"Guppy", "url": "https://dodo.ac/np/images/3/38/Guppy_NH_Icon.png"},
    {"species":"Hammerhead shark", "url": "https://dodo.ac/np/images/e/ec/Hammerhead_Shark_NH_Icon.png"},
    {"species":"Horse mackerel", "url": "https://dodo.ac/np/images/a/a3/Horse_Mackerel_NH_Icon.png"},
    {"species":"Killifish", "url": "https://dodo.ac/np/images/e/ea/Killifish_NH_Icon.png"},
    {"species":"King salmon", "url": "https://dodo.ac/np/images/e/e1/King_Salmon_NH_Icon.png"},
    {"species":"Koi", "url": "https://dodo.ac/np/images/2/2d/Koi_NH_Icon.png"},
    {"species":"Loach", "url": "https://dodo.ac/np/images/a/a5/Loach_NH_Icon.png"},
    {"species":"Mahi-mahi", "url": "https://dodo.ac/np/images/d/d6/Mahi-Mahi_NH_Icon.png"},
    {"species":"Mitten crab", "url": "https://dodo.ac/np/images/9/9d/Mitten_Crab_NH_Icon.png"},
    {"species":"Moray eel", "url": "https://dodo.ac/np/images/3/3e/Moray_Eel_NH_Icon.png"},
    {"species":"Napoleonfish", "url": "https://dodo.ac/np/images/3/30/Napoleonfish_NH_Icon.png"},
    {"species":"Neon tetra", "url": "https://dodo.ac/np/images/4/42/Neon_Tetra_NH_Icon.png"},
    {"species":"Nibble fish", "url": "https://dodo.ac/np/images/0/0b/Nibble_Fish_NH_Icon.png"},
    {"species":"Oarfish", "url": "https://dodo.ac/np/images/5/50/Oarfish_NH_Icon.png"},
    {"species":"Ocean sunfish", "url": "https://dodo.ac/np/images/e/eb/Ocean_Sunfish_NH_Icon.png"},
    {"species":"Olive flounder", "url": "https://dodo.ac/np/images/b/b3/Olive_Flounder_NH_Icon.png"},
    {"species":"Pale chub", "url": "https://dodo.ac/np/images/e/e2/Pale_Chub_NH_Icon.png"},
    {"species":"Pike", "url": "https://dodo.ac/np/images/9/9f/Pike_NH_Icon.png"},
    {"species":"Piranha", "url": "https://dodo.ac/np/images/c/c6/Piranha_NH_Icon.png"},
    {"species":"Pond smelt", "url": "https://dodo.ac/np/images/0/0f/Pond_Smelt_NH_Icon.png"},
    {"species":"Pop-eyed goldfish", "url": "https://dodo.ac/np/images/0/0d/Pop-Eyed_Goldfish_NH_Icon.png"},
    {"species":"Puffer fish", "url": "https://dodo.ac/np/images/e/ee/Puffer_Fish_NH_Icon.png"},
    {"species":"Rainbowfish", "url": "https://dodo.ac/np/images/e/e7/Rainbowfish_NH_Icon.png"},
    {"species":"Ranchu goldfish", "url": "https://dodo.ac/np/images/3/35/Ranchu_Goldfish_NH_Icon.png"},
    {"species":"Ray", "url": "https://dodo.ac/np/images/9/9b/Ray_NH_Icon.png"},
    {"species":"Red snapper", "url": "https://dodo.ac/np/images/c/c1/Red_Snapper_NH_Icon.png"},
    {"species":"Ribbon eel", "url": "https://dodo.ac/np/images/2/26/Ribbon_Eel_NH_Icon.png"},
    {"species":"Saddled bichir", "url": "https://dodo.ac/np/images/4/46/Saddled_Bichir_NH_Icon.png"},
    {"species":"Salmon", "url": "https://dodo.ac/np/images/c/ca/Salmon_NH_Icon.png"},
    {"species":"Saw shark", "url": "https://dodo.ac/np/images/4/45/Saw_Shark_NH_Icon.png"},
    {"species":"Sea bass", "url": "https://dodo.ac/np/images/7/7f/Sea_Bass_NH_Icon.png"},
    {"species":"Sea butterfly", "url": "https://dodo.ac/np/images/f/f7/Sea_Butterfly_NH_Icon.png"},
    {"species":"Sea horse", "url": "https://dodo.ac/np/images/d/dc/Sea_Horse_NH_Icon.png"},
    {"species":"Snapping turtle", "url": "https://dodo.ac/np/images/b/b1/Snapping_Turtle_NH_Icon.png"},
    {"species":"Soft-shelled turtle", "url": "https://dodo.ac/np/images/e/eb/Soft-Shelled_Turtle_NH_Icon.png"},
    {"species":"Squid", "url": "https://dodo.ac/np/images/b/bf/Squid_NH_Icon.png"},
    {"species":"Stringfish", "url": "https://dodo.ac/np/images/e/eb/Stringfish_NH_Icon.png"},
    {"species":"Sturgeon", "url": "https://dodo.ac/np/images/9/91/Sturgeon_NH_Icon.png"},
    {"species":"Suckerfish", "url": "https://dodo.ac/np/images/d/de/Suckerfish_NH_Icon.png"},
    {"species":"Surgeonfish", "url": "https://dodo.ac/np/images/c/cb/Surgeonfish_NH_Icon.png"},
    {"species":"Sweetfish", "url": "https://dodo.ac/np/images/6/6a/Sweetfish_NH_Icon.png"},
    {"species":"Tadpole", "url": "https://dodo.ac/np/images/b/bb/Tadpole_NH_Icon.png"},
    {"species":"Tilapia", "url": "https://dodo.ac/np/images/e/ef/Tilapia_NH_Icon.png"},
    {"species":"Tuna", "url": "https://dodo.ac/np/images/4/4b/Tuna_NH_Icon.png"},
    {"species":"Whale shark", "url": "https://dodo.ac/np/images/4/4f/Whale_Shark_NH_Icon.png"},
    {"species":"Yellow perch", "url": "https://dodo.ac/np/images/6/67/Yellow_Perch_NH_Icon.png"},
    {"species":"Zebra turkeyfish", "url": "https://dodo.ac/np/images/8/85/Zebra_Turkeyfish_NH_Icon.png"}


];


export default fishData